### PR TITLE
feature: fix skills are overflowing on about section.

### LINKED ISSUE #3: In mobile view, skills are overflowing on about section

### PR DESCRIPTION
**Pull request by dtakkiy**
## in a word.

This is a fix #3.

## merging this will improve this

fix skills overflow.

@shradhaagarwal01 さん, Please review.

### CODE REVIEW

**Comment by shradhaagarwal01** [comment]
I made some changes to the index.css file. This merge has conflict in the same. Please review this once.

**Comment by dtakkiy** [comment]
thank you for your advice🎉🎉🎉

conflict has been resolved.

Please review again.

**Comment by shradhaagarwal01** [comment]
This is not fixing the issue.
In mobile view, the "skill" section is overflowing on the "about" section. Kindly check. :)

**Comment by dtakkiy** [comment]
😱😱😱 

confirm one more time!

**Comment by shradhaagarwal01** [comment]
still not working

**Comment by dtakkiy** [comment]
add margin top for mobile to skills.

**Comment by shradhaagarwal01** [comment]
Very well done!

**Pull request merged**
